{{$runtime := "10s"}} # Job runtime
{{$kueue := true}} # Switch to disable kueue scheduler in jobs

global:
  gc: {{.GC}}
  gcMetrics: false
metricsEndpoints:

{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    indexer:
  - metrics: [metrics.yml]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch      
{{ end }}
{{ if eq .LOCAL_INDEXING "true" }}
  - metrics: [metrics.yml]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}
  
jobs:

{{ if eq .kueue true }}
  - name: prereqs
    jobIterations: 1
    namespace: kueue-scale
    namespacedIterations: false
    objects:

      - objectTemplate: cluster-queue.yml
        replicas: 1
        inputVars:
          CPU_QUOTA: 150
          MEMORY_QUOTA: 480Gi
          PODS_QUOTA: 700
      
      - objectTemplate: resource-flavor.yml
        replicas: 1
{{ end }}

  - name: small
    namespace: kueue-scale-s
    jobIterations: 1
    namespacedIterations: false
    qps: {{.QPS}}
    burst: {{.BURST}}
    preLoadImages: false
    preLoadPeriod: 15s
    objects:

      - objectTemplate: local-queue.yml
        replicas: 1

      - objectTemplate: job.yml
        replicas: 20
        inputVars:
          kueue: {{$kueue}}
          parallelism: 5
          runtime: {{$runtime}}
  
  - name: medium
    namespace: kueue-scale-m
    jobIterations: 1
    preLoadImages: false
    namespacedIterations: false
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:

      - objectTemplate: local-queue.yml
        replicas: 1

      - objectTemplate: job.yml
        replicas: 100
        inputVars:
          kueue: {{$kueue}}
          parallelism: 5
          runtime: {{$runtime}}

  - name: large
    namespace: kueue-scale-l
    jobIterations: 1
    preLoadImages: false
    namespacedIterations: false
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:

      - objectTemplate: local-queue.yml
        replicas: 1

      - objectTemplate: job.yml
        replicas: 200
        inputVars:
          kueue: {{$kueue}}
          parallelism: 5
          runtime: {{$runtime}}

  - name: extra-large
    namespace: kueue-scale-xl
    jobIterations: 1
    preLoadImages: false
    namespacedIterations: false
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:

      - objectTemplate: local-queue.yml
        replicas: 1

      - objectTemplate: job.yml
        replicas: 400
        inputVars:
          kueue: {{$kueue}}
          parallelism: 5
          runtime: {{$runtime}}
