{{$runtime := "10s"}}                 # Job runtime
{{$parallelism := env "PARALLELISM"}}

global:
  gc: {{.GC}}
  gcMetrics: false
  measurements:
  - name: jobLatency
metricsEndpoints:

{{ if .ES_SERVER }}
  - metrics: [metrics.yml]
    indexer:
      insecureSkipVerify: true
      esServers: [{{.ES_SERVER}}]
      defaultIndex: {{.ES_INDEX}}
      type: opensearch      
{{ end }}
{{ if eq .LOCAL_INDEXING "true" }}
  - metrics: [metrics.yml]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}
  
jobs:

{{ if eq .KUEUE "true" }}
  - name: prereqs
    jobIterations: 1
    preLoadImages: false
    namespacedIterations: false
    skipIndexing: true
    objects:

      - objectTemplate: cluster-queue.yml
        replicas: 1
        inputVars:
          CPU_QUOTA: 150
          MEMORY_QUOTA: 480Gi
          PODS_QUOTA: 2000
      
      - objectTemplate: resource-flavor.yml
        replicas: 1
{{ end }}

  - name: small
    namespace: kueue-scale-s
    jobIterations: 1
    namespacedIterations: false
    namespaceLabels:
       kueue.openshift.io/managed: "true"
    qps: {{.QPS}}
    burst: {{.BURST}}
    preLoadImages: false
    preLoadPeriod: 15s
    objects:

{{ if eq .KUEUE "true" }}
      - objectTemplate: local-queue.yml
        replicas: 1
{{ end }}

      - objectTemplate: job.yml
        replicas: {{div 100 $parallelism}}
        inputVars:
          kueue: {{.KUEUE}}
          parallelism: {{$parallelism}}
          runtime: {{$runtime}}
  
  - name: medium
    namespace: kueue-scale-m
    jobIterations: 1
    preLoadImages: false
    namespacedIterations: false
    namespaceLabels:
       kueue.openshift.io/managed: "true"
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:

{{ if eq .KUEUE "true" }}
      - objectTemplate: local-queue.yml
        replicas: 1
{{ end }}

      - objectTemplate: job.yml
        replicas: {{div 500 $parallelism}}
        inputVars:
          kueue: {{.KUEUE}}
          parallelism: {{$parallelism}}
          runtime: {{$runtime}}

  - name: large
    namespace: kueue-scale-l
    jobIterations: 1
    preLoadImages: false
    namespacedIterations: false
    namespaceLabels:
       kueue.openshift.io/managed: "true"
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:

{{ if eq .KUEUE "true" }}
      - objectTemplate: local-queue.yml
        replicas: 1
{{ end }}

      - objectTemplate: job.yml
        replicas: {{div 1000 $parallelism}}
        inputVars:
          kueue: {{.KUEUE}}
          parallelism: {{$parallelism}}
          runtime: {{$runtime}}

  - name: extra-large
    namespace: kueue-scale-xl
    jobIterations: 1
    preLoadImages: false
    namespacedIterations: false
    namespaceLabels:
       kueue.openshift.io/managed: "true"
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:

{{ if eq .KUEUE "true" }}
      - objectTemplate: local-queue.yml
        replicas: 1
{{ end }}

      - objectTemplate: job.yml
        replicas: {{div 2000 $parallelism}}
        inputVars:
          kueue: {{.KUEUE}}
          parallelism: {{$parallelism}}
          runtime: {{$runtime}}
