apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue-2
spec:
  namespaceSelector: {} # match all.
  cohort: "shared-cq"
  resourceGroups:
  - coveredResources: [pods]
    flavors:
    - name: "default"
      resources:
      - name: "pods"
        nominalQuota: 2
        lendingLimit: 2
