apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: shared-cluster-queue
spec:
  preemption:
    reclaimWithinCohort: Any
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 100
    withinClusterQueue: Never
  namespaceSelector: {} # match all.
  cohort: "team-ab"
  resourceGroups:
  - coveredResources: [cpu, memory, pods]
    flavors:
    - name: "default"
      resources:
      - name: "cpu"
        nominalQuota: {{.CPU_QUOTA}}
      - name: "memory"
        nominalQuota: {{.MEMORY_QUOTA}}
      - name: "pods"
        nominalQuota: {{.PODS_QUOTA}}