# Workload that creates a 11 cluster queues one shared and another ten that can borrow resources from the shared one
{{$runtime := "10s"}}
{{$parallelism := 5}}

global:
  gc: {{.GC}}
  gcMetrics: false
  measurements:
  - name: jobLatency
metricsEndpoints:

{{ if .ES_SERVER }}
  - metrics: [kueue-metrics.yml]
    indexer:
      insecureSkipVerify: true
      esServers: [{{.ES_SERVER}}]
      defaultIndex: {{.ES_INDEX}}
      type: opensearch      
{{ end }}
{{ if eq .LOCAL_INDEXING "true" }}
  - metrics: [kueue-metrics.yml]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}
  
jobs:

{{ if eq .KUEUE "true" }}
  - name: prereqs
    jobIterations: 1
    preLoadImages: false
    namespacedIterations: false
    skipIndexing: true
    qps: 10
    burst: 10
    objects:
     
      - objectTemplate: cluster-queue.yml
        replicas: 10
        inputVars:
          PODS_QUOTA: 400

      - objectTemplate: resource-flavor.yml
        replicas: 1
{{ end }}

  - name: kueue-scale
    namespace: kueue-scale
    jobIterations: 10
    preLoadImages: false # TODO
    namespacedIterations: true
    cleanup: true
    namespaceLabels:
      kueue.openshift.io/managed: {{.KUEUE}}
    qps: 10
    burst: 10
    objects:

{{ if eq .KUEUE "true" }}
      - objectTemplate: local-queue.yml
        replicas: 1
{{ end }}

      - objectTemplate: job.yml
        replicas: 100
        inputVars:
          kueue: {{.KUEUE}}
          parallelism: {{$parallelism}}
          runtime: {{$runtime}}
